# Generated by Django 6.0.4 on 2026-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='internship',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
